# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target '第三方原生分享' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 第三方原生分享

  target '第三方原生分享Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '第三方原生分享UITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'WechatOpenSDK'
pod "WeiboSDK", :git => "https://github.com/sinaweibosdk/weibo_ios_sdk.git"

end
